In [1]:
import numpy as np


In [2]:
x=np.array([[5,-9],[2,1]])
xt=x.transpose()

In [3]:
np.linalg.inv(np.matmul(xt, x))

array([[0.15500945, 0.08128544],
       [0.08128544, 0.05482042]])

In [4]:
px=np.matmul(np.matmul(x, np.linalg.inv(np.matmul(xt, x))),xt)
px

array([[ 1.00000000e+00,  0.00000000e+00],
       [-6.66133815e-16,  1.00000000e+00]])

In [5]:
z=np.array([[1],[4]])
zt=z.transpose()

In [6]:
zt

array([[1, 4]])

In [7]:
pz=np.matmul(np.matmul(z, np.linalg.inv(np.matmul(zt, z))),zt)
pz

array([[0.05882353, 0.23529412],
       [0.23529412, 0.94117647]])

In [8]:
np.matmul(pz, px)

array([[0.05882353, 0.23529412],
       [0.23529412, 0.94117647]])

In [9]:
np.matmul(px, pz)

array([[0.05882353, 0.23529412],
       [0.23529412, 0.94117647]])

In [10]:
px

array([[ 1.00000000e+00,  0.00000000e+00],
       [-6.66133815e-16,  1.00000000e+00]])

In [11]:
pz

array([[0.05882353, 0.23529412],
       [0.23529412, 0.94117647]])